### ISSUE TITLE
How can I create a Report that use this module?

### ISSUE THREAD

**Issue by picoroma** [RISE-GmbH/icingaweb2-module-checkreports#2]
I Have installed (correctly) the module and it's prerequisite:
![image](https://github.com/RISE-GmbH/icingaweb2-module-checkreports/assets/23618664/40696a29-0591-469a-901c-1665c1ecacaf)

But NOW I'm not sure on HOW to create a test report and make this module works...

I create some report the have service as output... but always I have the same output:
![image](https://github.com/RISE-GmbH/icingaweb2-module-checkreports/assets/23618664/0a9e078f-33e5-43b6-a992-2f22e4743de5)

**Comment by moreamazingnick** [comment]
Since you messaged me using the icinga community forum, I close that issue
